#!/usr/bin/env python3
"""
OpenFOAM AI Agent - 使用您的 KIMI API Key 启动
"""

import sys
import os
from pathlib import Path

# 您的 KIMI API Key
KIMI_API_KEY = "sk-Y4G2lAGkFIhUeLvfaQEi5RzOpYbupjhPtkbp0Cb0KQCS2Jnr"

# 设置路径
sys.path.insert(0, str(Path(__file__).parent / "openfoam_ai"))
sys.path.insert(0, str(Path(__file__).parent / "openfoam_ai" / "agents"))
sys.path.insert(0, str(Path(__file__).parent / "openfoam_ai" / "core"))

from prompt_engine import PromptEngine, ConfigRefiner
from critic_agent import CriticAgent
from case_manager import CaseManager, create_cavity_case
from mesh_quality_agent import MeshQualityChecker

def print_banner():
    print("=" * 70)
    print("")
    print("          OpenFOAM AI Agent - Real LLM Mode")
    print("                     [KIMI Powered]")
    print("")
    print("=" * 70)
    print()

def main():
    print_banner()
    
    # 初始化 KIMI LLM
    print("Initializing KIMI LLM...")
    try:
        engine = PromptEngine(
            provider="kimi",
            api_key=KIMI_API_KEY,
            model="moonshot-v1-8k"  # 使用可用模型
        )
        if engine.mock_mode:
            print("Warning: Fallback to mock mode")
        else:
            print("Success: Connected to KIMI LLM (moonshot-v1-8k)")
    except Exception as e:
        print(f"Error: {e}")
        print("Falling back to mock mode...")
        engine = PromptEngine(mock_mode=True)
    
    # 初始化其他组件
    case_manager = CaseManager("./my_cases")
    config_refiner = ConfigRefiner()
    critic = CriticAgent(use_llm=False)
    
    print("\nSystem ready!")
    print("Commands:")
    print("  - Create a cavity flow")
    print("  - Setup pipe simulation")
    print("  - help / exit")
    print()
    
    # 交互循环
    while True:
        try:
            user_input = input("> ").strip()
            if not user_input:
                continue
            
            if user_input.lower() in ["exit", "quit"]:
                print("\nGoodbye!")
                break
            
            if user_input.lower() in ["help", "?"]:
                print("\nExamples:")
                print('  - "Create a 2D lid-driven cavity flow"')
                print('  - "Setup a pipe flow simulation, Re=1000"')
                print('  - "Simulate flow over a cylinder"')
                print()
                continue
            
            # 创建算例
            if any(kw in user_input.lower() for kw in ["create", "setup", "build", "建立", "创建"]):
                print("\n[AI] Analyzing your request using KIMI LLM...")
                
                # 使用真实 LLM 解析
                config = engine.natural_language_to_config(user_input)
                config = config_refiner.refine(config)
                
                # Critic 审查
                print("\n[Review] Checking simulation plan...")
                report = critic.review(config)
                print(f"Score: {report.score}/100 | Verdict: {report.verdict.name}")
                
                # 显示配置
                print("\n[Config] Generated by KIMI:")
                print(f"  Case: {config.get('task_id', 'unnamed')}")
                print(f"  Physics: {config.get('physics_type')}")
                print(f"  Solver: {config.get('solver', {}).get('name')}")
                
                geom = config.get('geometry', {})
                res = geom.get('mesh_resolution', {})
                print(f"  Mesh: {res.get('nx')} x {res.get('ny')} x {res.get('nz')}")
                
                # 使用 LLM 解释配置
                if not engine.mock_mode:
                    print("\n[AI] Generating explanation...")
                    explanation = engine.explain_config(config)
                    print(explanation[:400])
                
                # 创建算例
                confirm = input("\nCreate this case? (y/n): ").strip().lower()
                if confirm in ["y", "yes"]:
                    case_name = config.get('task_id', 'case_' + str(hash(user_input) % 10000))
                    case_path = create_cavity_case(case_manager, case_name)
                    print(f"\n[OK] Case created: {case_path}")
                    
                    files = list(case_path.glob("**/*"))
                    print(f"Generated {len([f for f in files if f.is_file()])} files")
                else:
                    print("Cancelled")
            
            else:
                print("Unknown command. Try 'create', 'help', or 'exit'")
            
            print()
            
        except KeyboardInterrupt:
            print("\n\nGoodbye!")
            break
        except Exception as e:
            print(f"Error: {e}")

if __name__ == "__main__":
    main()
